/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.AmbilMatkul;
import backend.User;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class lihatMatkul extends javax.swing.JFrame implements Session{

    /**
     * Creates new form lihatMatkul
     */
    
    private User currentUser;
    
    public lihatMatkul() {
        initComponents();
        tampilkanTable();
    }
    
    public void setAtribute(User curUser){
        currentUser = curUser;
        String[] nama = currentUser.getNama().split(" ");
        labelNama.setText("Hello, " + nama[0]);
        labelNIM.setText(String.valueOf(currentUser.getNim()));
    }
    
    public boolean isLogin(){
       return ( currentUser == null );
    }
    
    public void doLogin(){
        this.setVisible(false);
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelNIM = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JLabel();
        btnProfile = new javax.swing.JLabel();
        btnLihatKrs = new javax.swing.JLabel();
        btnAmbilKrs = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 650, 350));

        labelNIM.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        labelNIM.setForeground(new java.awt.Color(255, 255, 255));
        labelNIM.setText("1831710119");
        getContentPane().add(labelNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 60, -1, -1));

        labelNama.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        labelNama.setForeground(new java.awt.Color(255, 255, 255));
        labelNama.setText("Ananda Dwi Prayoga");
        getContentPane().add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 40, -1, -1));

        btnKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarMouseClicked(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 93, 34));

        btnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfileMouseClicked(evt);
            }
        });
        getContentPane().add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 36, 40, 40));

        btnLihatKrs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLihatKrs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLihatKrsMouseClicked(evt);
            }
        });
        getContentPane().add(btnLihatKrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 126, 80, 20));

        btnAmbilKrs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAmbilKrs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAmbilKrsMouseClicked(evt);
            }
        });
        getContentPane().add(btnAmbilKrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 195, 80, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/custom – 6.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }//GEN-LAST:event_btnKeluarMouseClicked

    private void btnProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Home home = new Home();
        home.setHome(currentUser);
        home.setLocationRelativeTo(null);
        home.setVisible(true);
    }//GEN-LAST:event_btnProfileMouseClicked

    private void btnLihatKrsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLihatKrsMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        LihatKRS lihatKRS = new LihatKRS();
        lihatKRS.setAtribute(currentUser);
        lihatKRS.setLocationRelativeTo(null);
        lihatKRS.setVisible(true);
    }//GEN-LAST:event_btnLihatKrsMouseClicked

    private void btnAmbilKrsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAmbilKrsMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        TampilAmbilMatkul ambilMatkul = new TampilAmbilMatkul();
        ambilMatkul.setAtribute(currentUser);
        ambilMatkul.setLocationRelativeTo(null);
        ambilMatkul.setVisible(true);
    }//GEN-LAST:event_btnAmbilKrsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lihatMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lihatMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lihatMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lihatMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                lihatMatkul lMatkul = new lihatMatkul();
                if(lMatkul.isLogin()){
                    lMatkul.doLogin();
                    return;
                }
                lMatkul.setVisible(true);
            }
        });
    }
    
    private void tampilkanTable(){
        String[] kolom = {"ID Matkul", "Nama Mata Kuliah", "Jumlah Bobot SKS"};
        Object[] obj = new Object[3];
        ArrayList<AmbilMatkul> listMatkul = new AmbilMatkul().getAll();
        
        jTable1.setModel(new DefaultTableModel(new Object[][]{}, kolom));
        
        for(AmbilMatkul matkul : listMatkul){
            obj[0] = matkul.getIdMatkul();
            obj[1] = matkul.getNamaMatkul();
            obj[2] = matkul.getJumlahSks();
            
            ((DefaultTableModel) jTable1.getModel()).addRow(obj);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnAmbilKrs;
    private javax.swing.JLabel btnKeluar;
    private javax.swing.JLabel btnLihatKrs;
    private javax.swing.JLabel btnProfile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelNIM;
    private javax.swing.JLabel labelNama;
    // End of variables declaration//GEN-END:variables
}
