/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.User;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputNIM = new javax.swing.JTextField();
        inputPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        labelNotice = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputNIM.setFont(new java.awt.Font("Montserrat", 0, 13)); // NOI18N
        inputNIM.setBorder(null);
        inputNIM.setOpaque(false);
        inputNIM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNIMKeyTyped(evt);
            }
        });
        getContentPane().add(inputNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 165, 195, 28));

        inputPassword.setBorder(null);
        inputPassword.setOpaque(false);
        getContentPane().add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 225, 195, 28));

        jButton1.setBackground(new java.awt.Color(74, 99, 163));
        jButton1.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Masuk");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 279, 89, 34));

        labelNotice.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        labelNotice.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(labelNotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/custom – 1.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowLostFocus

    private void inputNIMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNIMKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyChar() == KeyEvent.VK_DELETE || evt.getKeyChar()== KeyEvent.VK_BACK_SPACE ){
            inputNIM.setEditable(true);
        }else{
            inputNIM.setEditable(false);
        }
    }//GEN-LAST:event_inputNIMKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (inputNIM.getText().isEmpty() && inputPassword.getText().isEmpty()){
            labelNotice.setText("Masukkan nim dan password");
            return;
        }else if(inputNIM.getText().isEmpty()){
            labelNotice.setText("Masukkan nim anda");
            return;
        }else if(inputPassword.getText().isEmpty()){
            labelNotice.setText("Masukkan password anda");
            return;
        }
        labelNotice.setText("");
        User user = new User(Integer.parseInt(inputNIM.getText()), inputPassword.getText());
        if (user.login()) {
            this.setVisible(false);
            Home home = new Home();
            home.setHome(user.getUserLogin());
            home.setLocationRelativeTo(null);
            home.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Akun anda tidak ditemukan");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login login = new Login();
                login.setLocationRelativeTo(null);
                login.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField inputNIM;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelNotice;
    // End of variables declaration//GEN-END:variables
}
