/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.AmbilMatkul;
import backend.User;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class TampilAmbilMatkul extends javax.swing.JFrame implements Session{

    /**
     * Creates new form AmbilMatkul
     */
    
    private User currentUser;
    private String[] ddSemester;
    private ArrayList<Integer> idMatkul = new ArrayList<>();
    
    public TampilAmbilMatkul() {
        initComponents();

    }
    
     public void setAtribute(User curUser){
        currentUser = curUser;
        String[] nama = currentUser.getNama().split(" ");
        labelNama.setText("Hello, " + nama[0]);
        labelNIM.setText(String.valueOf(currentUser.getNim()));
        setDropDownSemster();
        setDropDownMatkul();
    }
     
    public boolean isLogin(){
       return ( currentUser == null );
    }
    
    public void doLogin(){
        this.setVisible(false);
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbSemester = new javax.swing.JComboBox();
        btnKeluar = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelNIM = new javax.swing.JLabel();
        cbMatkul = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        searchMatkul = new javax.swing.JTextField();
        btnProfile = new javax.swing.JLabel();
        btnLihatKrs = new javax.swing.JLabel();
        btnLihatKrs1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JLabel();
        labelError = new javax.swing.JLabel();
        labelValidasi = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbSemester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSemesterActionPerformed(evt);
            }
        });
        getContentPane().add(cbSemester, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 630, 30));

        btnKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarMouseClicked(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 93, 34));

        labelNama.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        labelNama.setForeground(new java.awt.Color(255, 255, 255));
        labelNama.setText("Ananda Dwi Prayoga");
        getContentPane().add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 40, -1, -1));

        labelNIM.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        labelNIM.setForeground(new java.awt.Color(255, 255, 255));
        labelNIM.setText("1831710119");
        getContentPane().add(labelNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 60, -1, -1));

        cbMatkul.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMatkulActionPerformed(evt);
            }
        });
        getContentPane().add(cbMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 250, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID SKS", "Nama Mata Kuliah", "Bobot SKS"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 630, 200));

        jButton1.setBackground(new java.awt.Color(74, 99, 163));
        jButton1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tambahkan");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 235, 230, 35));

        searchMatkul.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        searchMatkul.setBorder(null);
        searchMatkul.setOpaque(false);
        searchMatkul.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(searchMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 170, 200, 30));

        btnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfileMouseClicked(evt);
            }
        });
        getContentPane().add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 36, 40, 40));

        btnLihatKrs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLihatKrs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLihatKrsMouseClicked(evt);
            }
        });
        getContentPane().add(btnLihatKrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 126, 80, 20));

        btnLihatKrs1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLihatKrs1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLihatKrs1MouseClicked(evt);
            }
        });
        getContentPane().add(btnLihatKrs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 160, 100, 20));

        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 166, 20, 30));

        labelError.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        labelError.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(labelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 205, 230, -1));

        labelValidasi.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        labelValidasi.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(labelValidasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 96, 620, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/custom – 7.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseClicked
        // TODO add your handling code here:
        doLogin();
    }//GEN-LAST:event_btnKeluarMouseClicked
    
    
    private void setDropDownSemster(){
        String[] smtr =  {"Pilih Semester","Semester 1","Semester 2","Semester 3","Semester 4","Semester 5","Semester 6","Semester 7","Semester 8"};
        ddSemester = smtr;
        cbSemester.setModel(new DefaultComboBoxModel(ddSemester));
    }
    
    private void setDropDownMatkul(){
        ArrayList<Object> listMatkul = new ArrayList();
        listMatkul.add("Pilih Mata Kuliah");
        idMatkul.add(-1);
        
        for(AmbilMatkul matkul : new AmbilMatkul().getAll()){
            listMatkul.add(matkul.getNamaMatkul());
            idMatkul.add(matkul.getIdMatkul());
        }
        cbMatkul.setModel(new DefaultComboBoxModel(listMatkul.toArray()));
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(cbMatkul.getSelectedIndex() == 0 && cbSemester.getSelectedIndex() == 0){
            labelValidasi.setText("Pilih semester dan matkul terlebih dahulu");
            return;
        }
        else if(cbSemester.getSelectedIndex() == 0){
            labelValidasi.setText("Pilih semester terlebih dahulu");
            return;
        }else if(cbMatkul.getSelectedIndex() == 0){
            labelValidasi.setText("Pilih matkul terlebih dahulu");
            return;
        }
        
        labelValidasi.setText("");
        AmbilMatkul ambilMatkul = new AmbilMatkul();
        ambilMatkul.setSemester(cbSemester.getSelectedIndex());
        ambilMatkul.setIdMatkul(idMatkul.get(cbMatkul.getSelectedIndex()));
        ambilMatkul.setUser(currentUser);
        ambilMatkul.insertKRS();
        tampilTable(new AmbilMatkul(cbSemester.getSelectedIndex(), currentUser).getMatkulByUsrSmtr());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMatkulActionPerformed
        // TODO add your handling code here:
        if(cbMatkul.getSelectedIndex() != 0) labelError.setText("");
        String selectedItem = cbMatkul.getSelectedItem().toString();
        
        if(selectedItem.equals("Pilih Mata Kuliah")) selectedItem = "";
        searchMatkul.setText(selectedItem);
    }//GEN-LAST:event_cbMatkulActionPerformed

    private void btnProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Home home = new Home();
        home.setHome(currentUser);
        home.setLocationRelativeTo(null);
        home.setVisible(true);
    }//GEN-LAST:event_btnProfileMouseClicked

    private void btnLihatKrsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLihatKrsMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        LihatKRS lihatKRS = new LihatKRS();
        lihatKRS.setAtribute(currentUser);
        lihatKRS.setLocationRelativeTo(null);
        lihatKRS.setVisible(true);
    }//GEN-LAST:event_btnLihatKrsMouseClicked

    private void btnLihatKrs1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLihatKrs1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        lihatMatkul lihatMatkul1 = new lihatMatkul();
        lihatMatkul1.setAtribute(currentUser);
        lihatMatkul1.setLocationRelativeTo(null);
        lihatMatkul1.setVisible(true);
    }//GEN-LAST:event_btnLihatKrs1MouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        for(AmbilMatkul matkul : new AmbilMatkul().getAll()){
            if (searchMatkul.getText().equalsIgnoreCase(matkul.getNamaMatkul())) {
                labelError.setText("");
                cbMatkul.setSelectedItem(matkul.getNamaMatkul());
                return;
            }
        }
        String paragraph = searchMatkul.getText() + " Tidak ditemukan";
        labelError.setText("<html><p style=\"width:180px\">"+paragraph+"</p></html>");
        cbMatkul.setSelectedIndex(0);
    }//GEN-LAST:event_btnSearchMouseClicked

    private void cbSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSemesterActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < ddSemester.length; i++){
            if (cbSemester.getSelectedItem().toString().equals(ddSemester[i]) ) {
                AmbilMatkul ambilMatkul = new AmbilMatkul(i, currentUser);
                tampilTable(ambilMatkul.getMatkulByUsrSmtr());
            }
        }
    }//GEN-LAST:event_cbSemesterActionPerformed
    
    private void tampilTable(ArrayList<AmbilMatkul> list){
        String[] kolom = {"ID SKS", "Nama Mata Kuliah","Bobot SKS"};
        Object[] object = new Object[3];
        
        jTable1.setModel(new DefaultTableModel(new Object[][]{}, kolom));
        
        for(AmbilMatkul am : list){
            object[0] = am.getId();
            object[1] = am.getNamaMatkul();
            object[2] = am.getJumlahSks();
            
            ((DefaultTableModel) jTable1.getModel()).addRow(object);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilAmbilMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilAmbilMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilAmbilMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilAmbilMatkul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TampilAmbilMatkul tampilAmbilMatkul = new TampilAmbilMatkul();
                if(tampilAmbilMatkul.isLogin()){
                    tampilAmbilMatkul.doLogin();
                    return;
                }
                tampilAmbilMatkul.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnKeluar;
    private javax.swing.JLabel btnLihatKrs;
    private javax.swing.JLabel btnLihatKrs1;
    private javax.swing.JLabel btnProfile;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JComboBox cbMatkul;
    private javax.swing.JComboBox cbSemester;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelNIM;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelValidasi;
    private javax.swing.JTextField searchMatkul;
    // End of variables declaration//GEN-END:variables
}
